yarnPath: .yarn/releases/yarn-4.4.0.cjs
packageExtensions:
  "@storybook/nextjs@*":
    dependencies:
      "webpack": "*"
  "@chromatic-com/storybook@*":
    dependencies:
      "@storybook/client-logger": "*"
      "@storybook/core-events": "*"
