enableScripts: false

packageExtensions:
  "@chromatic-com/storybook@*":
    dependencies:
      "@storybook/client-logger": "*"
      "@storybook/core-events": "*"
  "@storybook/nextjs@*":
    dependencies:
      webpack: "*"

yarnPath: .yarn/releases/yarn-4.4.0.cjs
